TriblerGUI/qt_resources/mainwindow.ui, TriblerGUI/tribler_window.py, TriblerGUI/widgets/graph_provider.py, TriblerGUI/widgets/trustpage.py
=> READY: Add the network widget in the user interface and show dummy graph

Tribler/Core/Modules/restapi/display_endpoint.py, Tribler/Test/GUI/widgets/__init__.py, Tribler/Test/GUI/widgets/trustdisplay/__init__.py, Tribler/Test/GUI/widgets/trustdisplay/test_trustdisplaypage_data_processing.py, TriblerGUI/widgets/trustdisplaypage.py
Implements issue #44 
In this PR, the HTTP request to the display endpoint is made. Moreover, the sizes for both the individual nodes and edges are calculated in a basic manner, which can be used for the visualization.
=> READY: Request and process Trust-Statistics

Tribler/community/multichain/community.py
=> READY: Add call to count in incremental page rank

Tribler/Test/Community/Multichain/test_multichain_community.py
The removed tests were not working at all and are therefore removed. In
another pull request, these tests are to be rewritten
=> Remove faulty tests from the testfile

Tribler/community/multichain/statistics/page_rank.py
I wrote a more elaborate documentation of the `IncrementalPageRank` class.
=> Add a comment explaining the workings of incremental PageRank

Tribler/Test/Community/Multichain/statistics/test_page_rank.py, Tribler/community/multichain/statistics/page_rank.py
Fixes #107.
I added tests for our PageRank implementation and fixed a division bug.
=> Use float division in calculating PageRank and add tests

Tribler/Test/Community/Multichain/test_multichain_community.py, Tribler/community/multichain/community.py, Tribler/community/multichain/statistics/statistics_database.py
=> Random test data in statistics database

Tribler/Test/Community/Multichain/statistics/test_page_rank.py, Tribler/community/multichain/statistics/page_rank.py
I added more unit tests and found some more bugs in the PageRank implementation.
=> Fix PageRank bugs and add unit tests

TriblerGUI/widgets/trustpage/js/process_data.js
In this PR, two bugs are fixed from within process_data.js. These
two bugs are a typo in max_page_rank and the way the pageranks are
sorted.
=> READY: Fix various bugs in process_data.js

Tribler/Test/Core/Modules/RestApi/test_display_endpoint.py
=> READY: Extract duplicate code in display endpoint tests

TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/process_data.js
Solves the first checkbox of: #129
=> Set node color based on page rank score

Tribler/Test/Community/Multichain/statistics/test_page_rank.py, Tribler/Test/Community/Multichain/test_multichain_community.py, Tribler/community/multichain/community.py, Tribler/community/multichain/statistics/page_rank.py
=> Fix pagerank bug

TriblerGUI/test/widgets/trustpage/js/test_drawing.js, TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/process_data.js
=> Set link stroke width based on data transmitted over the link

TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/style.css
In this PR, a basic question mark icon with hover functionality is
put into the Trust DIsplay window. When hovered over, a box pops up,
displaying basic information.
=> Add information icon to Trust Display

TriblerGUI/test/widgets/trustpage/js/test_drawing.js, TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/style_config.js
=> READY: Use a config file for styling nodes, links etc. instead of magic numbers and colors everywhere.

Tribler/Test/Community/Multichain/statistics/test_page_rank.py, Tribler/community/multichain/community.py, Tribler/community/multichain/statistics/page_rank.py
=> Add weights on edges to pagerank implementation

TriblerGUI/widgets/trustpage.py
=> READY: Remove white screen

Tribler/Core/Modules/restapi/multichain_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_multichain_network_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_multichain_statistics_endpoint.py, Tribler/community/multichain/community.py, Tribler/community/multichain/database.py
=> Fixed bug where no neighbors would show when viewing real time data

Tribler/Core/Modules/restapi/multichain_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_multichain_network_endpoint.py
In this PR, the introduced bug where the endpoint would throw an
internal server error when the MultiChain was not enabled whilst
retrieving dummy data, is fixed.
Fixes #184
=> READY: Fix MultiChain network endpoint bug

Tribler/Core/Modules/restapi/multichain_endpoint.py, TriblerGUI/test/widgets/trustpage/js/test_data_processor.js, TriblerGUI/test/widgets/trustpage/js/test_graph_to_tree.js, TriblerGUI/test/widgets/trustpage/js/test_radial.js, TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/data_processor.js, TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/graph_to_tree.js, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/radial.js, TriblerGUI/widgets/trustpage/js/request_data.js, TriblerGUI/widgets/trustpage/js/style_config.js, TriblerGUI/widgets/trustpage/js/utilities.js
=> Adding a radial layout

TriblerGUI/widgets/trustpage/style.css
=> Shrink graph in vertical direction as well

Tribler/Test/Community/Multichain/test_multichain_database.py
=> READY: Fix possible collision with random sequence numbers in database test

TriblerGUI/test/widgets/trustpage/js/test_data_processor.js, TriblerGUI/test/widgets/trustpage/js/test_drawing.js, TriblerGUI/widgets/trustpage/js/data_processor.js, TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/style_config.js
=> READY: Nodes change size based on total traffic in visible nodes

TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/style_config.js, TriblerGUI/widgets/trustpage/style.css
=> Set information label color based on element hovering over

Tribler/Test/Community/Multichain/test_multichain_database.py, Tribler/community/multichain/database.py
=> Symmetric edges (query data from neighbors as well)

TriblerGUI/widgets/trustpage/index.html
=> READY: Update question mark button tooltip text with newly introduced features

TriblerGUI/test/widgets/trustpage/js/test_drawing.js, TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/style_config.js
=> Change node and edge colors

TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_simulation.js
I took out the force simulation from main.js and moved it into a separate file.
=> READY: Refactor simulation

TriblerGUI/widgets/trustpage/js/drawing.js, TriblerGUI/widgets/trustpage/js/style_config.js
=> READY: Highlight edges on hover

Tribler/Test/Community/Multichain/test_multichain_community.py, Tribler/community/multichain/community.py, Tribler/community/multichain/statistics/page_rank.py
This PR fixes two bugs (KeyError and updating walks) within the
page_rank usage.
Fixes #228
=> READY: Fix two bugs within the page_rank algorithm

Tribler/Test/Community/Multichain/test_multichain_database.py, Tribler/community/multichain/community.py, Tribler/community/multichain/database.py
Changed the total_up and total_down methods in the database to one query that uses the different blocks instead of the total_up and total_down field in the blocks
Fixes #238
=> READY: Consistent traffic values

TriblerGUI/widgets/trustpage/style.css
=> READY: Disable possibility to select text

Tribler/Core/APIImplementation/LaunchManyCore.py, Tribler/Test/Community/Multichain/test_multichain_database.py, Tribler/community/multichain/community.py, Tribler/community/multichain/database.py
This PR enables the multichain crawler
=> READY: Real time crawling

Tribler/Core/Modules/restapi/multichain_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_multichain_statistics_endpoint.py
I missed two lines when rebasing our master branch. In this PR, I'm updating these lines.
=> WIP: Update call to check if MultiChain is enabled

TriblerGUI/test/widgets/trustpage/js/test_radial.js, TriblerGUI/widgets/trustpage/js/radial.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_simulation.js
=> READY: Improve radial force

Tribler/Test/Community/Multichain/test_multichain_database.py
=> Fix the neighbor test with unique sequence numbers

TriblerGUI/widgets/trustpage/js/radial_view/radial_link.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_node.js
=> READY: Fix d3 data updating

TriblerGUI/widgets/trustpage/js/data_processor.js
=> READY: Remove accidental merge conflict

TriblerGUI/test/widgets/trustpage/js/test_utilities.js, TriblerGUI/widgets/trustpage/js/utilities.js
=> READY: Fix format bytes bug and add tests

TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_navigation.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_node.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_simulation.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_stepping_animation.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_view.js, TriblerGUI/widgets/trustpage/js/request_data.js, TriblerGUI/widgets/trustpage/js/style_config.js, TriblerGUI/widgets/trustpage/style.css
=> READY: 'Back to You' button

Tribler/Core/Modules/restapi/trustchain_endpoint.py, Tribler/Test/Community/Triblerchain/test_database.py, Tribler/Test/Core/Modules/RestApi/test_trustchain_network_endpoint.py, Tribler/community/triblerchain/database.py
=> Add tests for uncovered lines

TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/radial.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_link.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_positioning.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_simulation.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_view.js
=> Refactor positioning

TriblerGUI/widgets/trustpage/help_page.css, TriblerGUI/widgets/trustpage/index.html, TriblerGUI/widgets/trustpage/js/help_page.js, TriblerGUI/widgets/trustpage/js/main.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_node.js, TriblerGUI/widgets/trustpage/js/style_config.js, TriblerGUI/widgets/trustpage/js/utilities.js, TriblerGUI/widgets/trustpage/style.css
=> Add help page

TriblerGUI/widgets/trustpage/js/radial_view/radial_link.js
=> Reverse link separator position

TriblerGUI/widgets/trustpage/js/main.js
=> Disable right mouseclick functionality

TriblerGUI/widgets/trustpage/js/radial_view/radial_inspector.js, TriblerGUI/widgets/trustpage/js/radial_view/radial_view.js, TriblerGUI/widgets/trustpage/style.css
=> READY: Add blocking policy text

Tribler/Test/Community/Triblerchain/test_community.py, Tribler/community/triblerchain/community.py, Tribler/community/triblerchain/database.py
In this commit, the bug with the total traffic changing when focusing
the node has been addressed and fixed.
Fixes #347
=> READY: Fix total traffic bug

TriblerGUI/test/widgets/trustpage/js/test_graph_to_tree.js, TriblerGUI/test/widgets/trustpage/js/test_radial.js
=> READY: Remove relative paths in javascript tests

TriblerGUI/widgets/network_explorer/js/radial_view/radial_node.js, TriblerGUI/widgets/network_explorer/js/style_config.js
The final marker size is now equal to the size of the marker.
=> READY: Change final marker size

TriblerGUI/widgets/network_explorer/js/help_page.js
Better code hub doesn't like methods with more than 6 arguments.
=> READY: Smaller unit interfaces

TriblerGUI/widgets/trustpagegraph.py
See https://github.com/Tribler/tribler/pull/2958#discussion_r123456753.
=> READY: Remove hex decoding in trust graph

Tribler/Core/Modules/restapi/trustchain_endpoint.py, Tribler/Test/Community/Triblerchain/test_database.py, Tribler/Test/Core/Modules/RestApi/test_trustchain_network_endpoint.py, Tribler/community/triblerchain/database.py
Fixes part of https://github.com/vandenheuvel/tribler/issues/312. This can be merged once https://github.com/vandenheuvel/tribler/issues/330 and https://github.com/vandenheuvel/tribler/issues/362 are closed.
=> Remove test code

TriblerGUI/test/widgets/network_explorer/js/test_utilities.js
See Martijn's comment in our [pull request](https://github.com/Tribler/tribler/pull/2958)
=> Minor styling improvements

Tribler/Test/Community/Triblerchain/test_database.py, Tribler/Test/Community/Triblerchain/test_triblerchain_utilities.py, Tribler/Test/Community/Trustchain/test_database.py, Tribler/Test/Community/Trustchain/test_trustchain_utilities.py, Tribler/Test/Core/Modules/RestApi/test_trustchain_endpoint.py, Tribler/Test/Core/Modules/RestApi/test_trustchain_network_endpoint.py, Tribler/community/triblerchain/database.py
Implements feedback from the Tribler repo
=> Tribler feedback
